swagger: '2.0'
info:
    title: VaccinationCare
    version: 1.0.0
    description: Hinda teenust
paths:
    /vaccinations:
        get:
            tags:
                - vaccine
            responses:
                '200':
                    description: Returns a list of Vaccinations
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json: |-
                            [
                                "Terminator 2",
                                "Minions",
                                "Devils wears a Prada",
                            ]
            summary: Get all the <Vaccine> in API
            description: Return all Vaccinations that are registered in API
        post:
            tags:
                - vaccine
            parameters:
                -
                    name: body
                    description: The <Vaccine> that is to be created.
                    schema:
                        $ref: '#/definitions/new-Vaccine'
                    in: body
                    required: true
            responses:
                '201':
                    description: Send 201 when <Vaccine> is successfully added to the database.
                    schema:
                        $ref: '#/definitions/new-Vaccine'
                '400':
                    description: 'Missing some parameter, please review your request data.'
                    schema:
                        $ref: '#/definitions/error'
            summary: Create a new <Vaccine> into the app
            description: 'Create a new <Vaccine> instance with its required details, for futher usage.'
    '/vaccinations/{VaccineID}':
        get:
            tags:
                - vaccine
            responses:
                '200':
                    description: Returns all details of the given <Vaccine>
            operationId: VaccineID
            summary: Get full details of a <Vaccine>
            description: Will return all details of a given <Vaccine> based on VaccineID given
        delete:
            tags:
                - vaccine
            parameters:
                -
                    name: body
                    description: Id of <Vaccine> to be removed from the app.
                    schema:
                        $ref: '#/definitions/delete-Vaccine'
                    in: body
                    required: true
            responses:
                '204':
                    description: Returns "No content" when remove of <Vaccine> is successful.
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: No Content
                '404':
                    description: 'Returns error, when <Vaccine> with specified ID does NOT exist'
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: Id not found
            summary: Delete a <Vaccine> from the App
            description: Deletes and entry from the app. NEVER TO BE SEEN AGAIN.
        parameters:
            -
                name: VaccineID
                description: ID of Vaccine
                in: path
                required: true
                type: string
definitions:
    new-Vaccine:
        title: Root Type for new-Vaccine
        description: ''
        required:
            - Appointment
            - BestBefore
            - Clinic
            - Description
            - Location
            - Name
        type: object
        properties:
            Name:
                type: string
            Description:
                type: string
            Clinic:
                type: string
            Appointment:
                type: string
            Location:
                type: string
            BestBefore:
                type: string
        example:
            Name: NewVaccineName
            Description: NewVaccineDescription
            Clinic: NewVaccineClinic
            Appointment: NewVaccineAppoitnment
            Location: NewVaccineLocation
            BestBefore: NewVaccineBestBefore
    error:
        title: Root Type for error
        description: ''
        type: object
        properties:
            error:
                type: string
        example:
            error: Error MessageThis data type is currently a complex object
    delete-Vaccine:
        title: Root Type for delete-Vaccine
        description: ''
        type: object
        properties:
            VaccineID:
                type: string
        example:
            VaccineID: 84c0f85e-dd2e-4b55-8945-a903b1b67811
